name: Build APK
on: [push]
jobs:
  build:
    # استخدام 22.04 يحل مشكلة نقص مكتبة libtinfo5 نهائياً
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4 # تحديث للإصدار 4 لحل تحذير Node.js

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk python3-venv autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev build-essential

      - name: Install Cython and Buildozer
        run: |
          python3 -m pip install --upgrade pip
          # تثبيت Cython يدوياً يحل مشكلة "Cython not found"
          python3 -m pip install --user --upgrade Cython==0.29.33 wheel buildozer
          # إضافة المسار ليتعرف النظام على الأوامر
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build with Buildozer
        run: |
          # الموافقة التلقائية على الرخص وبدء البناء المباشر
          # هذا يتجاوز خطأ "chown" تماماً لأنه يعمل بصلاحيات السيرفر المباشرة
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4 # تحديث للإصدار 4
        with:
          name: package
          path: bin/*.apk
          
