name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    # استخدام نسخة 22.04 لأنها الأكثر توافقاً مع أدوات الأندرويد حالياً
    runs-on: ubuntu-22.04 
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # النسخة الأكثر استقراراً لـ Kivy و Buildozer

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev \
            build-essential

      - name: Install Python Tools
        run: |
          pip install --upgrade pip
          # تثبيت نسخ محددة تمنع مشاكل الترجمة (Cython و Setuptools)
          pip install "setuptools<70.0.0" "cython<3.0.0"
          pip install buildozer

      - name: Build APK (Automatic License Accept)
        run: |
          # الموافقة التلقائية على تراخيص جوجل وبدء البناء
          yes | buildozer android debug
        env:
          APP_ACCEPT_SDK_LICENSE: "1"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: WorkshopMaster-Package
          path: bin/*.apk
          
